In [27]:
import pandas as pd
import importlib
import alerts

importlib.reload(alerts)

In [28]:
df = pd.read_csv("./data/final_risk_prioritization.csv", sep=";")

df.head()

,ID ANSSI,Titre ANSSI,Type,Date,CVE,Editeur,Produit,Versions affectées,CVSS,CVSS_completed,EPSS,EPSS_completed,risk_score,risk_priority,Lien CVE,Lien solution
0,CERTFR-2023-ALE-009,[MàJ] Multiples vulnérabilités dans Ivanti End...,Alerte,2023-07-26,CVE-2023-35078,Ivanti,Endpoint Manager Mobile,NaN,10.0,10.0,0.94482,0.94482,0.977928,CRITICAL,https://www.cve.org/CVERecord?id=CVE-2023-35078,https://forums.ivanti.com/s/article/CVE-2023-3...
1,CERTFR-2023-AVI-0584,Vulnérabilité dans Ivanti Endpoint Manager Mobile,Avis,2023-07-25,CVE-2023-35078,Ivanti,Endpoint Manager Mobile,NaN,10.0,10.0,0.94482,0.94482,0.977928,CRITICAL,https://www.cve.org/CVERecord?id=CVE-2023-35078,https://forums.ivanti.com/s/article/CVE-2023-3...
2,CERTFR-2023-AVI-0604,Vulnérabilité dans Ivanti Endpoint Manager Mobile,Avis,2023-07-31,CVE-2023-35078,Ivanti,Endpoint Manager Mobile,NaN,10.0,10.0,0.94482,0.94482,0.977928,CRITICAL,https://www.cve.org/CVERecord?id=CVE-2023-35078,https://forums.ivanti.com/s/article/CVE-2023-3...
3,CERTFR-2023-AVI-0793,Multiples vulnérabilités dans Progress WS_FTP ...,Avis,2023-09-29,CVE-2023-40044,Progress Software Corporation,WS_FTP Server,"8.8.0, 8.7.0",10.0,10.0,0.94449,0.94449,0.977796,CRITICAL,https://www.cve.org/CVERecord?id=CVE-2023-40044,https://community.progress.com/s/article/WS-FT...
4,CERTFR-2021-ALE-018,Vulnérabilité dans Atlassian Confluence Server...,Alerte,2021-09-06,CVE-2021-26084,"Atlassian, Atlassian","Confluence Server, Confluence Data Center","unspecified, 6.14.0, unspecified, 7.5.0, unspe...",NaN,10.0,0.94440,0.94440,0.977760,CRITICAL,https://www.cve.org/CVERecord?id=CVE-2021-26084,https://jira.atlassian.com/browse/CONFSERVER-6...

In [29]:
df[[
    "CVE",
    "Date",
    "Titre ANSSI",
    "Editeur",
    "Produit",
    "risk_priority",
    "risk_score"
]].head()

,CVE,Date,Titre ANSSI,Editeur,Produit,risk_priority,risk_score
0,CVE-2023-35078,2023-07-26,[MàJ] Multiples vulnérabilités dans Ivanti End...,Ivanti,Endpoint Manager Mobile,CRITICAL,0.977928
1,CVE-2023-35078,2023-07-25,Vulnérabilité dans Ivanti Endpoint Manager Mobile,Ivanti,Endpoint Manager Mobile,CRITICAL,0.977928
2,CVE-2023-35078,2023-07-31,Vulnérabilité dans Ivanti Endpoint Manager Mobile,Ivanti,Endpoint Manager Mobile,CRITICAL,0.977928
3,CVE-2023-40044,2023-09-29,Multiples vulnérabilités dans Progress WS_FTP ...,Progress Software Corporation,WS_FTP Server,CRITICAL,0.977796
4,CVE-2021-26084,2021-09-06,Vulnérabilité dans Atlassian Confluence Server...,"Atlassian, Atlassian","Confluence Server, Confluence Data Center",CRITICAL,0.977760

In [30]:
df[[
    "ID ANSSI",
    "Titre ANSSI",
    "Type",
    "Date",
    "CVE",
    "Editeur",
    "Produit",
    "CVSS_completed",
    "EPSS_completed",
    "risk_score",
    "risk_priority",
    "Lien CVE",
    "Lien solution"
]].head()

,ID ANSSI,Titre ANSSI,Type,Date,CVE,Editeur,Produit,CVSS_completed,EPSS_completed,risk_score,risk_priority,Lien CVE,Lien solution
0,CERTFR-2023-ALE-009,[MàJ] Multiples vulnérabilités dans Ivanti End...,Alerte,2023-07-26,CVE-2023-35078,Ivanti,Endpoint Manager Mobile,10.0,0.94482,0.977928,CRITICAL,https://www.cve.org/CVERecord?id=CVE-2023-35078,https://forums.ivanti.com/s/article/CVE-2023-3...
1,CERTFR-2023-AVI-0584,Vulnérabilité dans Ivanti Endpoint Manager Mobile,Avis,2023-07-25,CVE-2023-35078,Ivanti,Endpoint Manager Mobile,10.0,0.94482,0.977928,CRITICAL,https://www.cve.org/CVERecord?id=CVE-2023-35078,https://forums.ivanti.com/s/article/CVE-2023-3...
2,CERTFR-2023-AVI-0604,Vulnérabilité dans Ivanti Endpoint Manager Mobile,Avis,2023-07-31,CVE-2023-35078,Ivanti,Endpoint Manager Mobile,10.0,0.94482,0.977928,CRITICAL,https://www.cve.org/CVERecord?id=CVE-2023-35078,https://forums.ivanti.com/s/article/CVE-2023-3...
3,CERTFR-2023-AVI-0793,Multiples vulnérabilités dans Progress WS_FTP ...,Avis,2023-09-29,CVE-2023-40044,Progress Software Corporation,WS_FTP Server,10.0,0.94449,0.977796,CRITICAL,https://www.cve.org/CVERecord?id=CVE-2023-40044,https://community.progress.com/s/article/WS-FT...
4,CERTFR-2021-ALE-018,Vulnérabilité dans Atlassian Confluence Server...,Alerte,2021-09-06,CVE-2021-26084,"Atlassian, Atlassian","Confluence Server, Confluence Data Center",10.0,0.94440,0.977760,CRITICAL,https://www.cve.org/CVERecord?id=CVE-2021-26084,https://jira.atlassian.com/browse/CONFSERVER-6...

In [31]:
df["cluster"] = 0

df[["CVE", "Date", "Produit", "risk_priority", "risk_score", "cluster"]].head()

,CVE,Date,Produit,risk_priority,risk_score,cluster
0,CVE-2023-35078,2023-07-26,Endpoint Manager Mobile,CRITICAL,0.977928,0
1,CVE-2023-35078,2023-07-25,Endpoint Manager Mobile,CRITICAL,0.977928,0
2,CVE-2023-35078,2023-07-31,Endpoint Manager Mobile,CRITICAL,0.977928,0
3,CVE-2023-40044,2023-09-29,WS_FTP Server,CRITICAL,0.977796,0
4,CVE-2021-26084,2021-09-06,"Confluence Server, Confluence Data Center",CRITICAL,0.977760,0

In [32]:
df_mails = alerts.generer_fichiers_alertes(
    df,
    dossier_sortie="mails_generes",
    nb_jours=90,
    nombre_max=20
)

df_mails

,CVE,Date,Produit,Editeur,Priorité,Score de risque,Destinataires,Fichier généré
0,CVE-2026-43284,2026-06-05,Linux,Linux,HIGH,0.633348,linux.admin@example.com,mails_generes/alerte_1434_CVE-2026-43284.txt
1,CVE-2026-43500,2026-06-05,Linux,Linux,HIGH,0.629064,linux.admin@example.com,mails_generes/alerte_1473_CVE-2026-43500.txt
2,CVE-2026-43500,2026-06-05,Linux,Linux,HIGH,0.629064,linux.admin@example.com,mails_generes/alerte_1478_CVE-2026-43500.txt
3,CVE-2026-43284,2026-06-01,Linux,Linux,HIGH,0.633348,linux.admin@example.com,mails_generes/alerte_1436_CVE-2026-43284.txt
4,CVE-2026-43500,2026-06-01,Linux,Linux,HIGH,0.629064,linux.admin@example.com,mails_generes/alerte_1476_CVE-2026-43500.txt
5,CVE-2026-34197,2026-05-29,"Apache ActiveMQ Broker, Apache ActiveMQ All, A...",Apache Software Foundation,CRITICAL,0.843239,web.security@example.com,mails_generes/alerte_363_CVE-2026-34197.txt
6,CVE-2023-2640,2026-05-29,Ubuntu Kernel,Canonical,CRITICAL,0.837868,linux.admin@example.com,mails_generes/alerte_387_CVE-2023-2640.txt
7,CVE-2023-32629,2026-05-29,Ubuntu Kernel,Canonical,HIGH,0.773348,linux.admin@example.com,mails_generes/alerte_821_CVE-2023-32629.txt
8,CVE-2025-11953,2026-05-29,Unknow,Unknow,HIGH,0.710424,soc.general@example.com,mails_generes/alerte_1027_CVE-2025-11953.txt
9,CVE-2026-43284,2026-05-29,Linux,Linux,HIGH,0.633348,linux.admin@example.com,mails_generes/alerte_1435_CVE-2026-43284.txt
10,CVE-2025-14009,2026-05-29,nltk/nltk,nltk,HIGH,0.603512,soc.general@example.com,mails_generes/alerte_1661_CVE-2025-14009.txt
11,CVE-2026-0848,2026-05-29,nltk/nltk,nltk,HIGH,0.601228,soc.general@example.com,mails_generes/alerte_1717_CVE-2026-0848.txt
12,CVE-2023-2640,2026-05-22,Ubuntu Kernel,Canonical,CRITICAL,0.837868,linux.admin@example.com,mails_generes/alerte_388_CVE-2023-2640.txt
13,CVE-2023-32629,2026-05-22,Ubuntu Kernel,Canonical,HIGH,0.773348,linux.admin@example.com,mails_generes/alerte_817_CVE-2023-32629.txt
14,CVE-2026-43284,2026-05-22,Linux,Linux,HIGH,0.633348,linux.admin@example.com,mails_generes/alerte_1439_CVE-2026-43284.txt
15,CVE-2026-43284,2026-05-22,Linux,Linux,HIGH,0.633348,linux.admin@example.com,mails_generes/alerte_1440_CVE-2026-43284.txt
16,CVE-2026-43500,2026-05-22,Linux,Linux,HIGH,0.629064,linux.admin@example.com,mails_generes/alerte_1477_CVE-2026-43500.txt
17,CVE-2017-17485,2026-05-21,Unknown,Unknown,CRITICAL,0.892099,soc.general@example.com,mails_generes/alerte_194_CVE-2017-17485.txt
18,CVE-2017-7525,2026-05-21,jackson-databind,FasterXML,CRITICAL,0.869391,soc.general@example.com,mails_generes/alerte_278_CVE-2017-7525.txt
19,CVE-2023-44487,2026-05-21,Unknown,Unknown,CRITICAL,0.829620,soc.general@example.com,mails_generes/alerte_407_CVE-2023-44487.txt

In [33]:
df_mails.to_csv("resume_mails_generes.csv", sep=";", index=False)

In [34]:
fichier_exemple = df_mails["Fichier généré"].iloc[0]

with open(fichier_exemple, "r", encoding="utf-8") as f:
    contenu = f.read()

print(contenu)

To: linux.admin@example.com
Subject: [ALERTE ANSSI - HIGH] CVE-2026-43284

Bonjour,

Une vulnérabilité prioritaire et récente a été détectée sur un produit surveillé.

Produit(s) ou éditeur(s) détecté(s) : linux

Informations sur la vulnérabilité :
- ID ANSSI : CERTFR-2026-AVI-0695
- Titre ANSSI : Multiples vulnérabilités dans le noyau Linux d'Ubuntu
- Type : Avis
- Date : 2026-06-05
- CVE : CVE-2026-43284
- Éditeur : Linux
- Produit : Linux
- Versions affectées : cac2661c53f35cbe651bef9b07026a5a05ab8ce0, 4.11

Scores :
- CVSS complété : 8.8
- EPSS complété : 0.26337
- Score de risque : 0.633348
- Priorité : HIGH

Liens utiles :
- Lien CVE : https://www.cve.org/CVERecord?id=CVE-2026-43284
- Lien solution : https://git.kernel.org/stable/c/a6cb440f274a22456ef3e86b457344f1678f38f9

Recommandation :
Il est conseillé de vérifier rapidement si le produit concerné est utilisé dans le système d'information.
Si c'est le cas, il faut consulter la solution proposée et appliquer les correctifs disponibles.

Deux CVE récentes du même cluster KMeans :
- CVE-2026-43500 | Date : 2026-06-05 | Lien : https://www.cve.org/CVERecord?id=CVE-2026-43500
- CVE-2026-43037 | Date : 2026-06-05 | Lien : https://www.cve.org/CVERecord?id=CVE-2026-43037

Cordialement,
Système de veille ANSSI